# Site settings
title: Your awesome title
email: stein.tore.tosse@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog about what I do, learn and want to learn. 
  I also use this blog as a notebook of useful learings
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://steintore.github.io" # the base hostname & protocol for your site
twitter_username: steintt
github_username:  steintore

# Build settings
markdown: kramdown
