# Site settings
title: "I wish my smart house could blog for itself"
email: stein.tore.tosse@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog about what I learn, and what I want to learn.
  Also a blog to remember what I've done
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://steintore.github.io" # the base hostname & protocol for your site
twitter_username: steintt
github_username:  steintore

# Build settings
#markdown: kramdown

paginate: 4
paginate_path: "page:num"

markdown: rdiscount
permalink: pretty
highlighter: rouge